export const IMG_CDN_URL =
	"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
export const API_ENDPOINT =
	"https://www.swiggy.com/dapi/restaurants/list/v5?lat=12.9304278&lng=77.678404&page_type=DESKTOP_WEB_LISTING";
export const ITEM_IMG_CDN =
	"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/";
export const RESTAURANT_DETAILS_API =
	"https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=12.9304278&lng=77.678404&restaurantId=";
export const restaurantList = [
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "588860",
			name: "The Indian Food Story",
			uuid: "9884a6ee-b9e6-439f-8a1e-15cfd460f2ba",
			city: "1",
			area: "Bellandur",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "fgmragnnljavg9rkew13",
			cuisines: ["North Indian", "Punjabi", "Biryani", "Desserts"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 25,
			minDeliveryTime: 25,
			maxDeliveryTime: 25,
			slaString: "25 MINS",
			lastMileTravel: 1.5,
			slugs: {
				restaurant:
					"the-indian-food-story-bellandur-sarjapur-bellandur-sarjapur",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"227, Bellandur Main Rd, Bellandur, Bengaluru, Karnataka 560103, India",
			locality: "Bellandur",
			parentId: 294086,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5937091~p=1~eid=00000186-55f4-591f-0233-557200870100",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "588860",
				deliveryTime: 25,
				minDeliveryTime: 25,
				maxDeliveryTime: 25,
				lastMileTravel: 1.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.1",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "45754",
			name: "Dhaba Shaba",
			uuid: "ad69acd6-6f97-48e8-b2c8-0f658cd3ba81",
			city: "1",
			area: "Sarjapur Road",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "c5z4you4mdxnsdjxaig8",
			cuisines: ["North Indian", "Punjabi", "Thalis", "Indian"],
			tags: [],
			costForTwo: 25000,
			costForTwoString: "₹250 FOR TWO",
			deliveryTime: 26,
			minDeliveryTime: 26,
			maxDeliveryTime: 26,
			slaString: "26 MINS",
			lastMileTravel: 3.9000000953674316,
			slugs: {
				restaurant: "dhaba-shaba-bellandursarjapur-sarjapur-disabled",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"House No-71/1A, Shop No-3, Ground Floor Lingappa Reddy complex Kaikondrahalli Varthurhobli Carmelara, Devanahalli, Bangalore Rural (Karnataka), - 560035",
			locality: "Kaikondrahalli",
			parentId: 21531,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
					{
						meta: "15% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
					{
						meta: "15% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "15% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
					{
						meta: "15% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3.9 kms",
			hasSurge: false,
			sla: {
				restaurantId: "45754",
				deliveryTime: 26,
				minDeliveryTime: 26,
				maxDeliveryTime: 26,
				lastMileTravel: 3.9000000953674316,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.2",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "296209",
			name: "Anjarai Petti",
			uuid: "976f0234-8bcc-4808-9b0e-3cc1fa60c1af",
			city: "1",
			area: "Marathahalli",
			totalRatingsString: "50+ ratings",
			cloudinaryImageId: "bvsm2qdhsmma2zjfudka",
			cuisines: ["South Indian", "Chinese"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 40,
			minDeliveryTime: 40,
			maxDeliveryTime: 40,
			slaString: "40 MINS",
			lastMileTravel: 6.400000095367432,
			slugs: {
				restaurant: "anjarai-petti-marathahalli-marathahalli",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"Shan's Kitchen,SHOP NO.1 SITE, NO 39/1 NEW NO 4 GROUND FLOOR KUNDALAHALLI GATE ARVIND AVENUE AECS LAYOUT ROAD NEAR BANK OF BARODA BANGALORE ,Mahadevapura ,B.B.M.P East,Karnataka-560037",
			locality: "AECS Layout",
			parentId: 33621,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
					{
						meta: "Free ButterMilk on orders above ₹513",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
					{
						meta: "Free ButterMilk on orders above ₹513",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
					{
						meta: "Free ButterMilk on orders above ₹513",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "6.4 kms",
			hasSurge: false,
			sla: {
				restaurantId: "296209",
				deliveryTime: 40,
				minDeliveryTime: 40,
				maxDeliveryTime: 40,
				lastMileTravel: 6.400000095367432,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.6",
			totalRatings: 50,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "33395",
			name: "Nagarjuna",
			uuid: "732f701a-ad57-4fef-bef3-af3f790f6ffb",
			city: "1",
			area: "Marathahalli",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "wojet4oindf9pbomfjbr",
			cuisines: ["Andhra", "Biryani", "South Indian", "Beverages", "Desserts"],
			tags: [],
			costForTwo: 60000,
			costForTwoString: "₹600 FOR TWO",
			deliveryTime: 29,
			minDeliveryTime: 29,
			maxDeliveryTime: 29,
			slaString: "29 MINS",
			lastMileTravel: 3.700000047683716,
			slugs: {
				restaurant: "nagarjuna-marathahalli-marathahalli",
				city: "bangalore",
			},
			cityState: "1",
			address: "#88, outer ring road , Maratha halli",
			locality: "Outer Ring Road",
			parentId: 4168,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5948795~p=4~eid=00000186-55f4-591f-0233-557300870456",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "33395",
				deliveryTime: 29,
				minDeliveryTime: 29,
				maxDeliveryTime: 29,
				lastMileTravel: 3.700000047683716,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.3",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "393838",
			name: "Chinese Wok",
			uuid: "c6340f1e-0f91-4eca-b822-b64bf745e700",
			city: "1",
			area: "Sarjapur Road",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "gfsgzwzr1hlbkxafgv7a",
			cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
			tags: [],
			costForTwo: 25000,
			costForTwoString: "₹250 FOR TWO",
			deliveryTime: 31,
			minDeliveryTime: 31,
			maxDeliveryTime: 31,
			slaString: "31 MINS",
			lastMileTravel: 4.199999809265137,
			slugs: {
				restaurant:
					"chinese-wok-(wok-express)-bellandur-sarjapur-bellandur-sarjapur",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"SURVEY NO.9/1A, GROUND FLOOR, KASAVANAHALLI, BANGALORE, Mahadevapura , B.B.M.P East, Karnataka-560035",
			locality: "Kasavanahalli",
			parentId: 61955,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.1 kms",
			hasSurge: false,
			sla: {
				restaurantId: "393838",
				deliveryTime: 31,
				minDeliveryTime: 31,
				maxDeliveryTime: 31,
				lastMileTravel: 4.199999809265137,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.9",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "394230",
			name: "Rolls & Bowls Company",
			uuid: "ec07a318-3885-44eb-8603-b6790f43ee70",
			city: "1",
			area: "Sarjapur Road",
			totalRatingsString: "20+ ratings",
			cloudinaryImageId: "juetuulh2jnb76l3ewy1",
			cuisines: ["Indian", "North Indian", "Chinese"],
			tags: [],
			costForTwo: 25000,
			costForTwoString: "₹250 FOR TWO",
			deliveryTime: 33,
			minDeliveryTime: 33,
			maxDeliveryTime: 33,
			slaString: "33 MINS",
			lastMileTravel: 4.199999809265137,
			slugs: {
				restaurant:
					"rolls-and-bowls-company-bellandur_sarjapur2-bellandur_sarjapur2",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"SURVEY NO.9/1A, GROUND FLOOR, KASAVANAHALLI, BANGALORE, Mahadevapura , B.B.M.P East, Karnataka-560035",
			locality: "Kasavanahalli",
			parentId: 22080,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.1 kms",
			hasSurge: false,
			sla: {
				restaurantId: "394230",
				deliveryTime: 33,
				minDeliveryTime: 33,
				maxDeliveryTime: 33,
				lastMileTravel: 4.199999809265137,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.4",
			totalRatings: 20,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "444074",
			name: "Magnolia Bakery",
			uuid: "8fe485d2-f63a-4443-ac78-3acd3a547078",
			city: "1",
			area: "Bellandur",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "6f0945b8b18d9f4241dd1cd9a70e23d7",
			cuisines: ["Bakery", "Desserts", "Ice Cream"],
			tags: [],
			costForTwo: 50000,
			costForTwoString: "₹500 FOR TWO",
			deliveryTime: 24,
			minDeliveryTime: 24,
			maxDeliveryTime: 24,
			slaString: "24 MINS",
			lastMileTravel: 2.200000047683716,
			slugs: {
				restaurant: "magnolia-bakery-bellandur-sarjapur-bellandur-sarjapur",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"Unit 26A - 1, The Bay, RMZ Ecoworld, Marathahalli - Sarjapur Outer Ring Rd, Bengaluru, Karnataka 560103",
			locality: "RMZ Ecoworld",
			parentId: 267303,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5799693~p=7~eid=00000186-55f4-591f-0233-55740087072b",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "444074",
				deliveryTime: 24,
				minDeliveryTime: 24,
				maxDeliveryTime: 24,
				lastMileTravel: 2.200000047683716,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.6",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "580936",
			name: "EatFit",
			uuid: "091d48fb-2be8-4b59-aeb9-0e8ac0242858",
			city: "1",
			area: "Bellandur",
			totalRatingsString: "500+ ratings",
			cloudinaryImageId: "c769d3b4bb5a6a6a7d36eb28eacd00aa",
			cuisines: [
				"Healthy Food",
				"Pizzas",
				"North Indian",
				"Thalis",
				"Biryani",
				"Chinese",
			],
			tags: [],
			costForTwo: 27000,
			costForTwoString: "₹270 FOR TWO",
			deliveryTime: 24,
			minDeliveryTime: 24,
			maxDeliveryTime: 24,
			slaString: "24 MINS",
			lastMileTravel: 2.5,
			slugs: {
				restaurant: "eatfit-outer-ring-road-kadubeesanahalli",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"FIRSTFLOOR,20/5,GNS IKON ,KADUBISANAHALLI,OUTER RING ROAD,BANGALORE, Mahadevapura , B.B.M.P East, Karnataka-560103",
			locality: "Devarabisanahalli",
			parentId: 76139,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "580936",
				deliveryTime: 24,
				minDeliveryTime: 24,
				maxDeliveryTime: 24,
				lastMileTravel: 2.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.1",
			totalRatings: 500,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "384067",
			name: "AB's - Absolute Barbecues",
			uuid: "8908337d-abc5-44d6-8f62-88fe8715c937",
			city: "1",
			area: "Bellandur",
			totalRatingsString: "50+ ratings",
			cloudinaryImageId: "bt6nukss2ncdaz424ltx",
			cuisines: [
				"Barbecue",
				"Biryani",
				"Chinese",
				"Grill",
				"Mughlai",
				"North Indian",
				"Seafood",
				"Kebabs",
				"Pan-Asian",
			],
			tags: [],
			costForTwo: 40000,
			costForTwoString: "₹400 FOR TWO",
			deliveryTime: 29,
			minDeliveryTime: 29,
			maxDeliveryTime: 29,
			slaString: "29 MINS",
			lastMileTravel: 1.899999976158142,
			slugs: {
				restaurant:
					"ab’s-absolute-barbecues-bellandur-sarjapur-bellandur-sarjapur",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"First Floor, GRS Towers above Spencers Mart, Sarjapur Main Road, Bellandur, Bangalotre, Mahadevapura, B.B.M.P.East",
			locality: "Sarjapur Road",
			parentId: 387759,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
					{
						meta: "Free Crispy Fried Corn on orders above ₹399",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
					{
						meta: "Free Crispy Fried Corn on orders above ₹399",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
					{
						meta: "Free Crispy Fried Corn on orders above ₹399",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.8 kms",
			hasSurge: false,
			sla: {
				restaurantId: "384067",
				deliveryTime: 29,
				minDeliveryTime: 29,
				maxDeliveryTime: 29,
				lastMileTravel: 1.899999976158142,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.4",
			totalRatings: 50,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "12394",
			name: "Byg Brewski Brewing Company",
			uuid: "4e4319a4-d11f-45a7-8bf0-9d5d91e709f2",
			city: "1",
			area: "Sarjapur Road",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "dc2886690c60a7f3935ee4f58059ab3f",
			cuisines: [
				"Pizzas",
				"Burgers",
				"Pan-Asian",
				"North Indian",
				"Pastas",
				"Grill",
				"Biryani",
				"Mexican",
			],
			tags: [],
			costForTwo: 85000,
			costForTwoString: "₹850 FOR TWO",
			deliveryTime: 40,
			minDeliveryTime: 40,
			maxDeliveryTime: 40,
			slaString: "40 MINS",
			lastMileTravel: 4.599999904632568,
			slugs: {
				restaurant: "big-brewsky-bellandursarjapur",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"10 2A  Big Brewsky  Kaikondrahalli  Sarjapur road  Behind MK Retail  Bangalore  Karnataka 560035",
			locality: "Kaikondrahalli",
			parentId: 7382,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "FREE DELIVERY",
				shortDescriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Free Delivery",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "FREE DELIVERY",
						discountType: "FREE_DELIVERY",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5843497~p=10~eid=00000186-55f4-591f-0233-557500870a65",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "12394",
				deliveryTime: 40,
				minDeliveryTime: 40,
				maxDeliveryTime: 40,
				lastMileTravel: 4.599999904632568,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.3",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
];
